import { reflectKeys } from "@/app/shared/services";
const namespacedPrefix = "[GLOBAL]";

const mutationTypes = reflectKeys(
  [
    "GET_COUNTRIES_DATA_SUCCESS",
    "GET_COUNTRIES_DATA_REQUEST",
    "GET_COUNTRIES_DATA_ERROR",
    "GET_COUNTRIES_DATA_RESET",

    "GET_PAYMENTTYPE_DATA_SUCCESS",
    "GET_PAYMENTTYPE_DATA_REQUEST",
    "GET_PAYMENTTYPE_DATA_ERROR",
    "GET_PAYMENTTYPE_DATA_RESET",

    "GET_SHIPPINGMETHODS_DATA_SUCCESS",
    "GET_SHIPPINGMETHODS_DATA_REQUEST",
    "GET_SHIPPINGMETHODS_DATA_ERROR",
    "GET_SHIPPINGMETHODS_DATA_RESET",

    "GET_ROLES_DATA_REQUEST"
  ],
  namespacedPrefix
);

export const {
  GET_COUNTRIES_DATA_SUCCESS,
  GET_COUNTRIES_DATA_REQUEST,
  GET_COUNTRIES_DATA_ERROR,

  GET_PAYMENTTYPE_DATA_SUCCESS,
  GET_PAYMENTTYPE_DATA_REQUEST,
  GET_PAYMENTTYPE_DATA_ERROR,
  GET_PAYMENTTYPE_DATA_RESET,

  GET_SHIPPINGMETHODS_DATA_SUCCESS,
  GET_SHIPPINGMETHODS_DATA_REQUEST,
  GET_SHIPPINGMETHODS_DATA_ERROR,
  GET_SHIPPINGMETHODS_DATA_RESET,

  GET_ROLES_DATA_REQUEST
} = mutationTypes;
