import { reflectKeys } from "@/app/shared/services";
const namespacedPrefix = "[USERSLIST]";

const mutationTypes = reflectKeys(
  [
    "USERS_DATA_SUCCESS",
    "USERS_DATA_REQUEST",
    "USERS_DATA_ERROR",
    "USERS_DATA_RESET",
    "FETCH_CURRENT_USER",
    "STORE_CURRENT_USER",
    "STORE_USERS",
    "FETCH_ALL_USER",
    "USERS_DETAILS_ERROR",
    "USERS_DETAILS_REQUEST",
    "USERS_DETAILS_RESET",
    "USERS_DETAILS_SUCCESS",
    "GET_USERS_DETAILS_REQUEST",
    "UPDATE_USERS_DETAILS_REQUEST",
    "UPDATE_USERS_DETAILS_SUCCESS",
    "UPDATE_USERS_DETAILS_ERROR",
    "UPDATE_USERS_COMPANY_REQUEST",
    "UPDATE_USERS_COMPANY_SUCCESS",
    "UPDATE_USERS_COMPANY_ERROR",
    "RESET_USERS_PASSWORD_REQUEST",
    "REQUEST_USERS_PASSWORD_FOR_LOGGED_IN_USER"
  ],
  namespacedPrefix
);

export const {
  USERS_DATA_ERROR,
  USERS_DATA_REQUEST,
  USERS_DATA_RESET,
  USERS_DATA_SUCCESS,
  STORE_USERS,
  FETCH_CURRENT_USER,
  STORE_CURRENT_USER,
  FETCH_ALL_USER,
  USERS_DETAILS_ERROR,
  USERS_DETAILS_REQUEST,
  USERS_DETAILS_RESET,
  USERS_DETAILS_SUCCESS,
  GET_USERS_DETAILS_REQUEST,
  UPDATE_USERS_DETAILS_REQUEST,
  UPDATE_USERS_DETAILS_SUCCESS,
  UPDATE_USERS_DETAILS_ERROR,
  UPDATE_USERS_COMPANY_REQUEST,
  UPDATE_USERS_COMPANY_SUCCESS,
  UPDATE_USERS_COMPANY_ERROR,
  RESET_USERS_PASSWORD_SUCCESS,
  RESET_USERS_PASSWORD_ERROR,
  RESET_USERS_PASSWORD_REQUEST,
  REQUEST_USERS_PASSWORD_FOR_LOGGED_IN_USER
} = mutationTypes;
